#!/bin/bash
rsync -ax *.py servers.toml jellyfin1:auditor/
rsync -ax reports/*.py jellyfin1:auditor/reports/
rsync -ax comparison/*.py jellyfin1:auditor/comparison/
rsync -ax *.py servers.toml mediaserver:auditor/
rsync -ax reports/*.py mediaserver:auditor/reports/
rsync -ax comparison/*.py mediaserver:auditor/comparison/
