"""Shared CSS asset writer for static audit reports."""

from __future__ import annotations

from pathlib import Path


def write_css(path: Path) -> None:
    """Write the shared CSS asset."""
    path.write_text(_stylesheet(), encoding="utf-8")


def _stylesheet() -> str:
    """Return the shared report stylesheet."""
    return "\n".join(
        (
            ":root {",
            "  --bg: #f4f7fb;",
            "  --surface: #ffffff;",
            "  --surface-alt: #f8fafc;",
            "  --border: #dbe3ee;",
            "  --text: #1f2937;",
            "  --muted: #64748b;",
            "  --shadow: 0 10px 24px rgba(15, 23, 42, 0.08);",
            "  --accent: #2563eb;",
            "}",
            "* { box-sizing: border-box; }",
            "html { font-size: 80%; }",
            "body {",
            "  margin: 0;",
            "  background: var(--bg);",
            "  color: var(--text);",
            "  font-family: Arial, sans-serif;",
            "  line-height: 1.5;",
            "}",
            "a { color: var(--accent); text-decoration: none; }",
            "a:hover { text-decoration: underline; }",
            ".page-shell {",
            "  max-width: 1440px;",
            "  margin: 0 auto;",
            "  padding: 24px;",
            "}",
            ".site-nav {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 10px;",
            "  margin-bottom: 20px;",
            "}",
            ".nav-link {",
            "  display: inline-flex;",
            "  align-items: center;",
            "  padding: 10px 14px;",
            "  border-radius: 999px;",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  box-shadow: var(--shadow);",
            "  color: var(--text);",
            "  font-weight: 600;",
            "}",
            ".nav-link.is-active {",
            "  background: var(--accent);",
            "  border-color: var(--accent);",
            "  color: #ffffff;",
            "}",
            ".page-header { margin-bottom: 20px; }",
            ".page-header h1 { margin: 0 0 8px; font-size: 2rem; }",
            ".page-intro, .muted-text, .summary-card-subtitle { color: var(--muted); }",
            ".toolbar-card, .section-card, .panel-card, .about-card {",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  border-radius: 18px;",
            "  box-shadow: var(--shadow);",
            "  padding: 18px;",
            "  margin-bottom: 20px;",
            "}",
            ".toolbar-card {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 16px;",
            "  align-items: end;",
            "  justify-content: space-between;",
            "}",
            ".toolbar-controls {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 10px;",
            "  align-items: end;",
            "}",
            ".search-field {",
            "  display: flex;",
            "  flex-direction: column;",
            "  gap: 6px;",
            "  min-width: 280px;",
            "  font-weight: 600;",
            "}",
            ".search-field input {",
            "  padding: 12px 14px;",
            "  border: 1px solid var(--border);",
            "  border-radius: 12px;",
            "  font: inherit;",
            "}",
            ".toolbar-button {",
            "  padding: 12px 14px;",
            "  border-radius: 12px;",
            "  border: 1px solid var(--border);",
            "  background: var(--surface-alt);",
            "  cursor: pointer;",
            "  font: inherit;",
            "  font-weight: 600;",
            "}",
            ".summary-card-grid, .panel-grid {",
            "  display: grid;",
            "  gap: 16px;",
            "  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));",
            "  margin-bottom: 20px;",
            "}",
            ".panel-grid { grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); }",
            ".summary-card {",
            "  display: block;",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  border-radius: 18px;",
            "  box-shadow: var(--shadow);",
            "  padding: 18px;",
            "}",
            ".summary-card h3 { margin: 0 0 8px; }",
            ".summary-card-value { margin: 0; font-size: 1.8rem; font-weight: 700; }",
            ".summary-card-libraries { border-left: 6px solid #0f766e; }",
            ".summary-card-media { border-left: 6px solid #0369a1; }",
            ".summary-card-findings { border-left: 6px solid #4338ca; }",
            ".summary-card-error { border-left: 6px solid #b91c1c; }",
            ".summary-card-warning { border-left: 6px solid #b45309; }",
            ".summary-card-info { border-left: 6px solid #1d4ed8; }",
            ".summary-card-category { border-left: 6px solid #7c3aed; }",
            ".summary-card-library { border-left: 6px solid #047857; }",
            ".metric-pairs { display: grid; gap: 10px; }",
            ".metric-pairs div { display: flex; justify-content: space-between; gap: 12px; }",
            ".summary-list { margin: 0; padding-left: 18px; }",
            ".details-group {",
            "  margin-top: 14px;",
            "  border: 1px solid var(--border);",
            "  border-radius: 16px;",
            "  background: var(--surface-alt);",
            "  overflow: hidden;",
            "}",
            ".details-group summary {",
            "  display: flex;",
            "  align-items: center;",
            "  gap: 10px;",
            "  cursor: pointer;",
            "  padding: 14px 16px;",
            "  font-weight: 700;",
            "  list-style: none;",
            "}",
            ".details-group summary::-webkit-details-marker { display: none; }",
            ".details-group summary::before { content: '►'; color: var(--muted); }",
            ".details-group[open] > summary::before { content: '▼'; }",
            ".details-title { flex: 1 1 auto; }",
            ".details-count { color: var(--muted); }",
            ".details-body { padding: 0 16px 16px; }",
            ".table-shell { overflow-x: auto; }",
            ".findings-table {",
            "  width: 100%;",
            "  border-collapse: separate;",
            "  border-spacing: 0;",
            "  table-layout: fixed;",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  border-radius: 14px;",
            "}",
            ".findings-table th, .findings-table td {",
            "  padding: 10px 12px;",
            "  text-align: left;",
            "  vertical-align: top;",
            "  border-bottom: 1px solid var(--border);",
            "  word-break: break-word;",
            "}",
            ".findings-table thead th {",
            "  position: sticky;",
            "  top: 0;",
            "  z-index: 1;",
            "  background: #eef4fb;",
            "}",
            ".findings-table tbody tr:nth-child(even) { background: #fbfdff; }",
            ".findings-table tbody tr:last-child td { border-bottom: none; }",
            ".sort-button {",
            "  width: 100%;",
            "  border: none;",
            "  background: transparent;",
            "  padding: 0;",
            "  text-align: left;",
            "  font: inherit;",
            "  font-weight: 700;",
            "  cursor: pointer;",
            "}",
            ".finding-link { font-weight: 600; }",
            ".severity-badge {",
            "  display: inline-flex;",
            "  padding: 4px 10px;",
            "  border-radius: 999px;",
            "  font-size: 0.78rem;",
            "  font-weight: 700;",
            "}",
            ".severity-error { background: #fee2e2; color: #b91c1c; }",
            ".severity-warning { background: #ffedd5; color: #b45309; }",
            ".severity-info { background: #dbeafe; color: #1d4ed8; }",
            "@media (max-width: 900px) {",
            "  .page-shell { padding: 16px; }",
            "  .toolbar-card, .section-card, .panel-card, .about-card { padding: 16px; }",
            "}",
        )
    )
