"""Shared CSS asset writer for static audit reports."""

from __future__ import annotations

from pathlib import Path


def write_css(path: Path) -> None:
    """Write the shared stylesheet."""
    path.write_text(_stylesheet(), encoding="utf-8")


def _stylesheet() -> str:
    """Return the shared report stylesheet."""
    return "\n".join(
        (
            ":root {",
            "  --bg: #f6f8fa;",
            "  --surface: #ffffff;",
            "  --surface-alt: #f8fafc;",
            "  --border: #d0d7de;",
            "  --text: #1f2328;",
            "  --muted: #57606a;",
            "  --shadow: 0 8px 24px rgba(31, 35, 40, 0.08);",
            "  --accent: #0969da;",
            "  --danger: #b42318;",
            "  --success: #1a7f37;",
            "}",
            "* { box-sizing: border-box; }",
            "html { font-size: 80%; }",
            "body {",
            "  margin: 0;",
            "  background: var(--bg);",
            "  color: var(--text);",
            "  font-family: Arial, sans-serif;",
            "  line-height: 1.45;",
            "}",
            "a { color: var(--accent); text-decoration: none; }",
            "a:hover { text-decoration: underline; }",
            ".page-shell {",
            "  max-width: 1600px;",
            "  margin: 0 auto;",
            "  padding: 24px;",
            "}",
            ".sticky-header {",
            "  position: sticky;",
            "  top: 0;",
            "  z-index: 10;",
            "  background: rgba(246, 248, 250, 0.96);",
            "  backdrop-filter: blur(8px);",
            "  padding-bottom: 12px;",
            "}",
            ".site-nav {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 10px;",
            "  margin-bottom: 12px;",
            "}",
            ".nav-link {",
            "  display: inline-flex;",
            "  align-items: center;",
            "  padding: 10px 14px;",
            "  border-radius: 999px;",
            "  border: 1px solid var(--border);",
            "  background: var(--surface);",
            "  box-shadow: var(--shadow);",
            "  color: var(--text);",
            "  font-weight: 600;",
            "}",
            ".nav-link.is-active {",
            "  background: var(--accent);",
            "  border-color: var(--accent);",
            "  color: #ffffff;",
            "}",
            ".breadcrumbs { margin-bottom: 12px; }",
            ".breadcrumbs ol {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 8px;",
            "  list-style: none;",
            "  margin: 0;",
            "  padding: 0;",
            "}",
            ".breadcrumbs li + li::before {",
            "  content: '/';",
            "  color: var(--muted);",
            "  margin-right: 8px;",
            "}",
            ".page-header-card, .toolbar-card, .section-card, .about-card {",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  border-radius: 16px;",
            "  box-shadow: var(--shadow);",
            "  padding: 16px;",
            "  margin-bottom: 16px;",
            "}",
            ".page-header-card h1 {",
            "  margin: 0 0 8px;",
            "  font-size: 2rem;",
            "}",
            ".page-intro, .muted-text, .summary-card-subtitle { color: var(--muted); }",
            ".toolbar-card {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 16px;",
            "  align-items: end;",
            "  justify-content: space-between;",
            "}",
            ".toolbar-controls {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 10px;",
            "  align-items: end;",
            "}",
            ".search-field {",
            "  display: flex;",
            "  flex-direction: column;",
            "  gap: 6px;",
            "  min-width: 280px;",
            "  font-weight: 600;",
            "}",
            ".search-field input {",
            "  padding: 10px 12px;",
            "  border: 1px solid var(--border);",
            "  border-radius: 10px;",
            "  font: inherit;",
            "}",
            ".toolbar-button {",
            "  padding: 10px 12px;",
            "  border-radius: 10px;",
            "  border: 1px solid var(--border);",
            "  background: var(--surface-alt);",
            "  cursor: pointer;",
            "  font: inherit;",
            "  font-weight: 600;",
            "}",
            ".summary-card-grid {",
            "  display: grid;",
            "  gap: 14px;",
            "  grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));",
            "  margin-bottom: 16px;",
            "}",
            ".summary-card {",
            "  display: block;",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  border-radius: 16px;",
            "  box-shadow: var(--shadow);",
            "  padding: 16px;",
            "}",
            ".summary-card h3 { margin: 0 0 8px; }",
            ".summary-card-value { margin: 0; font-size: 1.55rem; font-weight: 700; }",
            ".summary-card-libraries { border-left: 5px solid #0f766e; }",
            ".summary-card-media { border-left: 5px solid #0369a1; }",
            ".summary-card-findings { border-left: 5px solid #4338ca; }",
            ".summary-card-server { border-left: 5px solid #4f46e5; }",
            ".summary-card-timestamp { border-left: 5px solid #64748b; }",
            ".summary-card-library { border-left: 5px solid #047857; }",
            ".summary-card-check { border-left: 5px solid #7c3aed; }",
            ".details-group {",
            "  margin-top: 14px;",
            "  border: 1px solid var(--border);",
            "  border-radius: 14px;",
            "  background: var(--surface-alt);",
            "  overflow: hidden;",
            "}",
            ".details-group summary {",
            "  display: flex;",
            "  align-items: center;",
            "  gap: 10px;",
            "  cursor: pointer;",
            "  padding: 14px 16px;",
            "  font-weight: 700;",
            "  list-style: none;",
            "}",
            ".details-group summary::-webkit-details-marker { display: none; }",
            ".details-group summary::before { content: '►'; color: var(--muted); }",
            ".details-group[open] > summary::before { content: '▼'; }",
            ".details-title { flex: 1 1 auto; }",
            ".details-count { color: var(--muted); }",
            ".details-body { padding: 0 16px 16px; }",
            ".table-shell { overflow-x: auto; }",
            ".data-table {",
            "  width: 100%;",
            "  border-collapse: separate;",
            "  border-spacing: 0;",
            "  table-layout: fixed;",
            "  background: var(--surface);",
            "  border: 1px solid var(--border);",
            "  border-radius: 12px;",
            "}",
            ".data-table th, .data-table td {",
            "  padding: 8px 10px;",
            "  text-align: left;",
            "  vertical-align: top;",
            "  border-bottom: 1px solid var(--border);",
            "  word-break: break-word;",
            "}",
            ".data-table thead th {",
            "  position: sticky;",
            "  top: 0;",
            "  z-index: 1;",
            "  background: #eef4fb;",
            "}",
            ".data-table tbody tr:nth-child(even) { background: #fbfdff; }",
            ".data-table tbody tr:last-child td { border-bottom: none; }",
            ".sort-button {",
            "  width: 100%;",
            "  border: none;",
            "  background: transparent;",
            "  padding: 0;",
            "  text-align: left;",
            "  font: inherit;",
            "  font-weight: 700;",
            "  cursor: pointer;",
            "}",
            ".status-label {",
            "  display: inline-flex;",
            "  align-items: center;",
            "  gap: 4px;",
            "  font-weight: 600;",
            "}",
            ".status-present { color: var(--success); }",
            ".status-missing { color: var(--danger); }",
            ".severity-badge {",
            "  display: inline-flex;",
            "  align-items: center;",
            "  justify-content: center;",
            "  min-width: 54px;",
            "  padding: 4px 8px;",
            "  border-radius: 999px;",
            "  font-size: 0.78rem;",
            "  font-weight: 700;",
            "}",
            ".severity-error { background: #fee2e2; color: #b91c1c; }",
            ".severity-warning { background: #ffedd5; color: #b45309; }",
            ".severity-info { background: #dbeafe; color: #1d4ed8; }",
            ".empty-row td { color: var(--muted); }",
            "@media (max-width: 900px) {",
            "  .page-shell { padding: 16px; }",
            "  .page-header-card, .toolbar-card, .section-card, .about-card { padding: 14px; }",
            "}",
        )
    )
