"""Shared CSS asset writer for static audit reports."""

from __future__ import annotations

from pathlib import Path


def write_css(path: Path) -> None:
    """Write the shared stylesheet."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_stylesheet(), encoding="utf-8")


def _stylesheet() -> str:
    """Return the shared report stylesheet."""
    return "\n".join(
        (
            ":root {",
            "  --bg: #f6f8fa;",
            "  --surface: #ffffff;",
            "  --surface-alt: #f8fafc;",
            "  --border: #d0d7de;",
            "  --text: #1f2328;",
            "  --muted: #57606a;",
            "  --shadow: 0 8px 24px rgba(31, 35, 40, 0.08);",
            "  --accent: #0969da;",
            "  --danger: #b42318;",
            "  --success: #1a7f37;",
            "  --header-bg: rgba(246, 248, 250, 0.96);",
            "  --table-head: #eef4fb;",
            "  --table-stripe: #fbfdff;",
            "  --input-bg: #ffffff;",
            "  --diff-row: #fff8de;",
            "  --diff-cell: #ffd666;",
            "  --diff-strong: #ffe7a3;",
            "  --diff-text: #5f370e;",
            "}",
            ':root[data-theme="dark"] {',
            "  --bg: #0d1117;",
            "  --surface: #161b22;",
            "  --surface-alt: #1f2937;",
            "  --border: #30363d;",
            "  --text: #e6edf3;",
            "  --muted: #9da7b3;",
            "  --shadow: 0 10px 28px rgba(0, 0, 0, 0.35);",
            "  --accent: #58a6ff;",
            "  --danger: #ff7b72;",
            "  --success: #3fb950;",
            "  --header-bg: rgba(13, 17, 23, 0.94);",
            "  --table-head: #1b2430;",
            "  --table-stripe: #111827;",
            "  --input-bg: #0d1117;",
            "  --diff-row: #3b2f17;",
            "  --diff-cell: #6b4f1d;",
            "  --diff-strong: #8b6914;",
            "  --diff-text: #fff3c4;",
            "}",
            "* { box-sizing: border-box; }",
            "html { font-size: 80%; }",
            "body { margin: 0; background: var(--bg); color: var(--text); font-family: Arial, sans-serif; line-height: 1.45; }",
            "a { color: var(--accent); text-decoration: none; }",
            "a:hover { text-decoration: underline; }",
            ".page-shell { max-width: 1600px; margin: 0 auto; padding: 24px; }",
            ".sticky-header { position: sticky; top: 0; z-index: 10; background: var(--header-bg); backdrop-filter: blur(8px); padding-bottom: 12px; }",
            ".site-nav { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; margin-bottom: 12px; }",
            ".nav-server-name { display: inline-flex; align-items: center; padding: 10px 14px; font-weight: 700; color: var(--text); }",
            ".nav-link { display: inline-flex; align-items: center; padding: 10px 14px; border-radius: 999px; border: 1px solid var(--border); background: var(--surface); box-shadow: var(--shadow); color: var(--text); font-weight: 600; }",
            ".nav-link.is-active { background: var(--accent); border-color: var(--accent); color: #ffffff; }",
            ".theme-toggle { margin-left: auto; display: inline-flex; align-items: center; gap: 12px; padding: 10px 14px; border-radius: 999px; border: 1px solid var(--border); background: var(--surface); box-shadow: var(--shadow); color: var(--text); }",
            ".theme-toggle-control { display: inline-flex; align-items: center; gap: 10px; font-weight: 600; }",
            ".theme-toggle-control input { margin: 0; accent-color: var(--accent); }",
            ".theme-toggle-value { color: var(--muted); font-weight: 600; }",
            ".breadcrumbs { margin-bottom: 12px; }",
            ".breadcrumbs ol { display: flex; flex-wrap: wrap; gap: 8px; list-style: none; margin: 0; padding: 0; }",
            ".breadcrumbs li + li::before { content: '/'; color: var(--muted); margin-right: 8px; }",
            ".page-header-card, .toolbar-card, .section-card, .about-card { background: var(--surface); border: 1px solid var(--border); border-radius: 16px; box-shadow: var(--shadow); padding: 16px; margin-bottom: 16px; }",
            ".page-header-actions { display: flex; justify-content: flex-end; margin-bottom: 12px; }",
            ".page-header-card h1 { margin: 0 0 8px; font-size: 2rem; }",
            ".page-intro, .muted-text, .summary-card-subtitle { color: var(--muted); }",
            ".toolbar-card { display: flex; flex-wrap: wrap; gap: 16px; align-items: end; justify-content: space-between; }",
            ".toolbar-controls { display: flex; flex-wrap: wrap; gap: 10px; align-items: end; }",
            ".search-field { display: flex; flex-direction: column; gap: 6px; min-width: 280px; font-weight: 600; }",
            ".search-field input { padding: 10px 12px; border: 1px solid var(--border); border-radius: 10px; font: inherit; background: var(--input-bg); color: var(--text); }",
            ".toolbar-button { padding: 10px 12px; border-radius: 10px; border: 1px solid var(--border); background: var(--surface-alt); color: var(--text); cursor: pointer; font: inherit; font-weight: 600; }",
            ".summary-card-grid { display: grid; gap: 14px; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); margin-bottom: 16px; }",
            ".summary-card { display: block; background: var(--surface); border: 1px solid var(--border); border-radius: 16px; box-shadow: var(--shadow); padding: 16px; }",
            ".summary-card h3 { margin: 0 0 8px; }",
            ".summary-card-value { margin: 0; font-size: 1.55rem; font-weight: 700; }",
            ".summary-card-libraries { border-left: 5px solid #0f766e; }",
            ".summary-card-media { border-left: 5px solid #0369a1; }",
            ".summary-card-findings { border-left: 5px solid #4338ca; }",
            ".summary-card-server { border-left: 5px solid #4f46e5; }",
            ".summary-card-timestamp { border-left: 5px solid #64748b; }",
            ".summary-card-library { border-left: 5px solid #047857; }",
            ".summary-card-check { border-left: 5px solid #7c3aed; }",
            ".table-shell { overflow-x: auto; }",
            ".data-table { width: 100%; border-collapse: separate; border-spacing: 0; table-layout: auto; background: var(--surface); border: 1px solid var(--border); border-radius: 12px; }",
            ".data-table th, .data-table td { padding: 8px 10px; text-align: left; vertical-align: top; border-bottom: 1px solid var(--border); word-break: break-word; }",
            ".data-table th { word-break: normal; }",
            ".data-table .sort-button { white-space: nowrap; }",
            ".data-table thead th { position: sticky; top: 0; z-index: 1; background: var(--table-head); }",
            ".data-table tbody tr:nth-child(even) { background: var(--table-stripe); }",
            ".data-table tbody tr:last-child td { border-bottom: none; }",
            ".comparison-table .empty-row td { white-space: normal; word-break: normal; }",
            ".table-scroll-shell { max-height: 28rem; overflow: auto; }",
            ".table-section-header { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; justify-content: space-between; margin-bottom: 12px; }",
            ".table-section-header h2 { margin: 0; }",
            ".table-row-count { color: var(--muted); font-weight: 400; }",
            ".table-filter-button { white-space: nowrap; }",
            ".data-table tr.comparison-diff-row td { background: var(--diff-row) !important; }",
            ".data-table tr.comparison-diff-row td:first-child, .data-table tr.comparison-diff-row td:nth-child(2) { background: var(--diff-strong) !important; color: var(--diff-text) !important; font-weight: 700; }",
            ".data-table td.comparison-diff { background: var(--diff-cell) !important; color: var(--diff-text) !important; font-weight: 700; }",
            ".sort-button { width: 100%; border: none; background: transparent; color: inherit; padding: 0; text-align: left; font: inherit; font-weight: 700; cursor: pointer; }",
            ".status-label { display: inline-flex; align-items: center; gap: 4px; font-weight: 600; }",
            ".status-present { color: var(--success); }",
            ".status-missing { color: var(--danger); }",
            ".empty-row td { color: var(--muted); }",
            "@media (max-width: 900px) { .page-shell { padding: 16px; } .page-header-card, .toolbar-card, .section-card, .about-card { padding: 14px; } .theme-toggle { margin-left: 0; width: 100%; justify-content: space-between; } }",
        )
    )
